# Generated by Django 3.2 on 2021-06-23 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('p', 'چاپ شده'), ('n', 'چاپ نشده ')], max_length=1)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('time', models.DateTimeField()),
                ('slug', models.SlugField(max_length=12, unique=True)),
            ],
        ),
    ]
