# Generated by Django 3.2 on 2021-06-24 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_artile_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artile',
            options={'verbose_name_plural': 'نظرات من'},
        ),
        migrations.AlterField(
            model_name='artile',
            name='description',
            field=models.TextField(verbose_name='ایجاد متن'),
        ),
        migrations.AlterField(
            model_name='artile',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='artile',
            name='name',
            field=models.CharField(max_length=20, verbose_name='اسم نویسنده '),
        ),
        migrations.AlterField(
            model_name='artile',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='artile',
            name='status',
            field=models.CharField(choices=[('p', 'چاپ شده'), ('n', 'چاپ نشده ')], max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='artile',
            name='title',
            field=models.CharField(max_length=30, verbose_name='نام عنوان'),
        ),
    ]
