# Generated by Django 3.2 on 2021-07-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210624_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='دسته بندی ')),
                ('status_garegory', models.BooleanField(default=True, verbose_name='وضعیت ')),
                ('slug_garegory', models.SlugField(max_length=12, unique=True, verbose_name='شماره ')),
            ],
            options={
                'verbose_name_plural': 'دسته بندی های من ',
            },
        ),
        migrations.AddField(
            model_name='artile',
            name='category',
            field=models.ManyToManyField(related_name='article', to='blog.Category', verbose_name='دسته بندی'),
        ),
    ]
