# Generated by Django 3.2 on 2021-07-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210704_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug_garegory',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='artile',
            name='category',
            field=models.ManyToManyField(related_name='articles', to='blog.Category', verbose_name='دسته بندی'),
        ),
    ]
